apiVersion: kubedb.com/v1alpha2
kind: Redis
metadata:
  name: polar-redis
  namespace: demo
spec:
  version: "6.2.5"
  storageType: Durable
  storage:
    storageClassName: "default"
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
