apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- github.com/polarbookshop/edge-service/k8s?ref=main

patchesStrategicMerge:
- patch-env.yml
- patch-ingress.yml
- patch-resources.yml
- patch-volumes.yml

configMapGenerator:
- behavior: merge
  files:
  - application-prod.yml
  name: edge-config

images:
- name: edge-service
  newName: ghcr.io/cboschmans-code/edge-service
  newTag: 79c61761f84d6e3ce7384ba49a7962bfb1f19cb2

replicas:
- count: 1
  name: edge-service
