apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- github.com/polarbookshop/edge-service/k8s?ref=main

patchesStrategicMerge:
- patch-env.yml
- patch-ingress.yml
- patch-resources.yml
- patch-volumes.yml

configMapGenerator:
- behavior: merge
  files:
  - application-prod.yml
  name: edge-config

images:
- name: edge-service
  newName: ghcr.io/cboschmans-code/edge-service
  newTag: b67155f17619aeb8f886f86d5fcc24a7e90da99f

replicas:
- count: 1
  name: edge-service
